collector_task:
  name: Collect Personal Project Information
  description: >
    Based on the initial message '{initial_message}', collect detailed information about the person by:
    Finding out their first name and last name their location, meaning country and city, company and email. 
    Ask questions in a natural way.
    Store all collected information in a structured format.
  expected_output: >
    All required fields of person.
#  output_json: PersonalInformationOutput --> This is set when the Agent is created in code.
  output_file: person.json
  agent: information_collector
  human_input: false

summarizer_task:
  name: Create Person Summary
  description: >
    Transform the collected personal information into a natural introduction by:
    1. Reading through the collected name and location details
    2. Creating a natural language introduction about the person
  expected_output: >
    A brief, natural sentence introduction that presents the person's name, location, company and email.
  agent: information_summarizer
  context:
    - collector_task
